# MongoDB configuration for TLS and authorization (Docker-friendly logging)
storage:
  dbPath: /data/db
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 2

systemLog:
  destination: stdout
  timeStampFormat: iso8601-utc
  verbosity: 0

net:
  port: 27017
  bindIpAll: true
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/ssl/mongo/mongo.pem
    CAFile: /etc/ssl/mongo/ca.pem
    allowConnectionsWithoutCertificates: true

replication:
  replSetName: "replica-set-1"

security:
  authorization: enabled
  clusterAuthMode: keyFile
  keyFile: /replication/keyfile

processManagement:
  fork: false
